### ISSUE TITLE
2025-12-10 not exists after 8:00 UTC

### ISSUE THREAD

**Issue by nojitsi** [fawazahmed0/exchange-api#144]
<img width="744" height="170" alt="Image" src="https://github.com/user-attachments/assets/327470b9-bc24-4ef3-b1db-3fa7d29b29f7" />

none of the currencies exists

<img width="1115" height="456" alt="Image" src="https://github.com/user-attachments/assets/4b70c3bd-73dd-49a9-b120-c06d36f983b8" />

can i do something to help you with that?
i really like your api, i think its simple, but yet very effective solution, which allows lots of projects to cut costs.
let me know, if i can do something for you.

**Comment by jamper91a** [comment]
https://github.blog/changelog/2025-12-09-npm-classic-tokens-revoked-session-based-auth-and-cli-token-management-now-available/

**Comment by fawazahmed0** [comment]
Should be fixed now.

**Comment by nojitsi** [comment]
@fawazahmed0 Seems to be fixed, current day is in the place, but previous is still 404 on cdn =(

**Comment by hansemannn** [comment]
@fawazahmed0, you are great, thank you! Two open issues here if you allow:

- https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@2025-12-11/v1/currencies/usd.min.json => works
- https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@2025-12-10/v1/currencies/usd.min.json => does not work
- https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/usd.min.json => still shows from 2 days ago

EDIT 12/12/2025: `@latest` now seems up-to-date again!

**Comment by janvS4D** [comment]
yeah, 2025-12-10 still doesnt work

**Comment by SniperWolfRaven** [comment]
@fawazahmed0 for the following currencies

https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/nzd.json

Is not working as expected, latest version is outdated, please check about this regard.

Thanks

**Comment by nojitsi** [comment]
@SniperWolfRaven I didn't understood regards what issue, you writing about, and how to test it not clear. It seems issue is unrelated, if you have some case, please create separate issue for that.

**Comment by danilocubrovic** [comment]
https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@2025-12-10/v1/currencies/usd.min.json
still dont have data

**Comment by fawazahmed0** [comment]
Github actions was [failing](https://github.com/fawazahmed0/exchange-api/actions/runs/20084784944) on `2025-12-10`. That's why the data is not available.
There is not much I could do to get the `2025-12-10` data back

**Comment by nojitsi** [comment]
@fawazahmed0 There is really nothing can be done to restore data? It is only available for the current day before publish?
